import Head from "next/head";
import { Header } from "../components";
import { useEffect } from "react";
import { API_REQUEST } from "../services/api.service";
import { GetServerSideProps } from "next";

export default function Home(props: HomeProps): JSX.Element {
  useEffect(() => {
    fetch(API_REQUEST.trending)
      .then((res) => res.json())
      .then((data) => console.log(data));
  }, []);

  return (
    <div className="relative h-[200vh]">
      <Head>
        <title>Home | Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main>
        {/* NOTE - HERO */}
        <section>
          {/* Row */}
          {/* BigRow */}
          {/* Row */}
          {/* BigRow */}
        </section>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const trending = await fetch(API_REQUEST.trending).then((res) => res.json());

  return {
    props: {
      trending,  
    },
  };
};

interface HomeProps {
  trending: any;
}
